python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-APNews.csv 0
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-APNews.csv 1
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-APNews.csv 2
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-APNews.csv 3
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-APNews.csv 4
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-APNews.csv 5
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-APNews.csv 6
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-APNews-tfidf.csv 0
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-APNews-tfidf.csv 1
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-APNews-tfidf.csv 2
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-APNews-tfidf.csv 3
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-APNews-tfidf.csv 4
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-APNews-tfidf.csv 5
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-APNews-tfidf.csv 6
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-Wiki.csv 0
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-Wiki.csv 1
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-Wiki.csv 2
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-Wiki.csv 3
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-Wiki.csv 4
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-Wiki.csv 5
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-Wiki.csv 6
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-Wiki-tfidf.csv 0
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-Wiki-tfidf.csv 1
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-Wiki-tfidf.csv 2
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-Wiki-tfidf.csv 3
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-Wiki-tfidf.csv 4
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-Wiki-tfidf.csv 5
python3 model_search.py /home/FCAM/dmcconnell/Social_media_mining/data_files/word_embedings-Wiki-tfidf.csv 6
